AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: hello_world
            CodeUri: hello_world
            Handler: app.lambda_handler
            Runtime: python3.7
            Events:
                Get:
                    Type: Api
                    Properties:
                        Path: /hello/{name}
                        Method: get

Outputs:
    HelloWorldEndpoint:
        Description: "Hello World function HTTPS endpoint"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
