AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: hello_world
            CodeUri: hello_world
            Handler: app.lambda_handler
            Runtime: python3.7
            Events:
                Get:
                    Type: Api
                    Properties:
                        Path: /hello/{name}
                        Method: get

    CreateUrlFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: create_url
            CodeUri: create_url
            Handler: app.lambda_handler
            Runtime: python3.7
            Events:
                Post:
                    Type: Api
                    Properties:
                        Path: /short
                        Method: post
                        RestApiId: !Ref ShortenerApi
            Environment:
                Variables:
                    TABLE_NAME: !Ref DynamoDBTable
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref DynamoDBTable

    DynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: short-ids
            BillingMode: PAY_PER_REQUEST
            KeySchema:
                - AttributeName: short_id
                  KeyType: HASH
            AttributeDefinitions:
                - AttributeName: short_id
                  AttributeType: S
            StreamSpecification:
                StreamViewType: NEW_IMAGE

    GetUrlFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: get_url
            CodeUri: get_url
            Handler: app.lambda_handler
            Runtime: python3.7
            Events:
                Get:
                    Type: Api
                    Properties:
                        Path: /short/{short_id}
                        Method: get
                        RestApiId: !Ref ShortenerApi
            Environment:
                Variables:
                    TABLE_NAME: !Ref DynamoDBTable
            Policies:
                - DynamoDBReadPolicy:
                      TableName: !Ref DynamoDBTable

    ShortenerApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            Cors:
                AllowMethods: "'POST,OPTIONS'"
                AllowHeaders: "'content-type'"
                AllowOrigin: "'*'"

    PreviewFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: preview
            CodeUri: preview
            Handler: app.lambda_handler
            Runtime: python3.7
            Events:
                DynamoDBEvent:
                    Type: DynamoDB
                    Properties:
                        Stream:
                          !GetAtt DynamoDBTable.StreamArn
                        StartingPosition: TRIM_HORIZON
                        BatchSize: 10
                    Environment:
                        Variables:
                            DYNAMODB_TABLE_NAME: !Ref PreviewTable
            Environment:
                Variables:
                    TABLE_NAME: !Ref PreviewTable
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref PreviewTable

    PreviewTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: url-shortener-preview
            BillingMode: PAY_PER_REQUEST
            KeySchema:
                - AttributeName: url
                  KeyType: HASH
            AttributeDefinitions:
                - AttributeName: url
                  AttributeType: S

Outputs:
    ShortURLApigwURL:
        Description: "API Gateway endpoint URL for Prod environment for Create URL Function"
        Value: !Sub "https://${ShortenerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/short"
