AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: hello_world
            CodeUri: hello_world
            Handler: app.lambda_handler
            Runtime: python3.7
            Events:
                Get:
                    Type: Api
                    Properties:
                        Path: /hello/{name}
                        Method: get

    CreateUrlFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: create_url
            CodeUri: create_url
            Handler: app.lambda_handler
            Runtime: python3.7
            AutoPublishAlias: live
            Tracing: Active
            Events:
                Post:
                    Type: Api
                    Properties:
                        Path: /short
                        Method: post
                        RestApiId: !Ref ShortenerApi
                        Auth:
                            Authorizer: CognitoAuthorizer
            Environment:
                Variables:
                    TABLE_NAME: !Ref DynamoDBTable
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref DynamoDBTable
            DeploymentPreference:
                Type: Canary10Percent5Minutes
                Alarms:
                    - !Ref AliasErrorMetricGreaterThanZeroAlarm
                    - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm

    DynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: short-ids
            BillingMode: PAY_PER_REQUEST
            KeySchema:
                - AttributeName: short_id
                  KeyType: HASH
            AttributeDefinitions:
                - AttributeName: short_id
                  AttributeType: S
            StreamSpecification:
                StreamViewType: NEW_IMAGE

    GetUrlFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: get_url
            CodeUri: get_url
            Handler: app.lambda_handler
            Runtime: python3.7
            Tracing: Active
            Events:
                Get:
                    Type: Api
                    Properties:
                        Path: /short/{short_id}
                        Method: get
                        RestApiId: !Ref ShortenerApi
            Environment:
                Variables:
                    TABLE_NAME: !Ref DynamoDBTable
            Policies:
                - DynamoDBReadPolicy:
                      TableName: !Ref DynamoDBTable

    ShortenerApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            Cors:
                AllowMethods: "'POST,OPTIONS'"
                AllowHeaders: "'content-type, authorization'"
                AllowOrigin: "'*'"
            Auth:
                Authorizers:
                    CognitoAuthorizer:
                        UserPoolArn: !GetAtt UserPool.Arn
            TracingEnabled: true

    PreviewFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: preview
            CodeUri: preview
            Handler: app.lambda_handler
            Runtime: python3.7
            Events:
                DynamoDBEvent:
                    Type: DynamoDB
                    Properties:
                        Stream:
                          !GetAtt DynamoDBTable.StreamArn
                        StartingPosition: TRIM_HORIZON
                        BatchSize: 10
                    Environment:
                        Variables:
                            DYNAMODB_TABLE_NAME: !Ref PreviewTable
            Environment:
                Variables:
                    TABLE_NAME: !Ref PreviewTable
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref PreviewTable

    PreviewTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: url-shortener-preview
            BillingMode: PAY_PER_REQUEST
            KeySchema:
                - AttributeName: url
                  KeyType: HASH
            AttributeDefinitions:
                - AttributeName: url
                  AttributeType: S

    UserPool:
        Type: AWS::Cognito::UserPool
        Properties:
            AutoVerifiedAttributes:
                - email
            EmailVerificationSubject: 'Your verification code'
            EmailVerificationMessage: 'Your code is {####}'
            UserPoolName: ShortenerUsers
            Policies:
                PasswordPolicy:
                    MinimumLength: 8
            UsernameAttributes:
                - email
            Schema:
                - AttributeDataType: String
                  Name: email
                  Required: false

    UserPoolClient:
        Type: AWS::Cognito::UserPoolClient
        Properties:
            UserPoolId: !Ref UserPool
            ClientName: ShortenerUsersClient
            GenerateSecret: false

    AliasErrorMetricGreaterThanZeroAlarm:
        Type: "AWS::CloudWatch::Alarm"
        Properties:
            AlarmDescription: Lambda Function Error > 0
            ComparisonOperator: GreaterThanThreshold
            Dimensions:
                - Name: Resource
                  Value: !Sub "${CreateUrlFunction}:live"
                - Name: FunctionName
                  Value: !Ref CreateUrlFunction
            EvaluationPeriods: 2
            MetricName: Errors
            Namespace: AWS/Lambda
            Period: 60
            Statistic: Sum
            Threshold: 0

    LatestVersionErrorMetricGreaterThanZeroAlarm:
        Type: "AWS::CloudWatch::Alarm"
        Properties:
            AlarmDescription: Lambda Function Error > 0
            ComparisonOperator: GreaterThanThreshold
            Dimensions:
                - Name: Resource
                  Value: !Sub "${CreateUrlFunction}:live"
                - Name: FunctionName
                  Value: !Ref CreateUrlFunction
                - Name: ExecutedVersion
                  Value: !GetAtt CreateUrlFunction.Version.Version
            EvaluationPeriods: 2
            MetricName: Errors
            Namespace: AWS/Lambda
            Period: 60
            Statistic: Sum
            Threshold: 0

    SlowFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: slow
            CodeUri: slow
            Handler: app.lambda_handler
            Runtime: python3.7
            ReservedConcurrentExecutions: 1
            DeadLetterQueue:
                Type: SQS
                TargetArn: !GetAtt DeadLetterQueue.Arn
            Events:
                Post:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt BufferQueue.Arn
                        BatchSize: 1
                        Enabled: true

    BufferFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: buffer
            CodeUri: buffer
            Handler: app.lambda_handler
            Runtime: python3.7
            Events:
                Get:
                    Type: Api
                    Properties:
                        Path: /slow
                        Method: get
            Environment:
                Variables:
                    QUEUE_URL: !Ref BufferQueue
            Policies:
                - SQSSendMessagePolicy:
                    QueueName: !GetAtt BufferQueue.QueueName
                - SQSSendMessagePolicy:
                    QueueName: !GetAtt DeadLetterQueue.QueueName

    BufferQueue:
        Type: AWS::SQS::Queue

    DeadLetterQueue:
        Type: AWS::SQS::Queue
Outputs:
    HelloWorldEndpoint:
        Description: "Hello World function HTTPS endpoint"
        Value: !Sub "https://${ShortenerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
    ShortURLEndpoint:
        Description: "Short URL functions HTTPS endpoint"
        Value: !Sub "https://${ShortenerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/short"
    SlowEndpoint:
        Description: "Slow functions HTTPS endpoint"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/slow"
    UserPoolId:
        Description: "Id of the Cognito User Pool to be referenced in Clients"
        Value: !Ref UserPool
    UserPoolClientId:
        Description: "Id of the Cognito User Pool Client"
        Value: !Ref UserPoolClient
